### ISSUE TITLE
FAO ETo calculation hourly - need delta

### ISSUE THREAD

**Issue by cp-boettcher** [mullenkamp/ETo#4]
Hello, 

I try to use this package with an hourly data set. With 
| R_s | T_mean | RH_mean | n_sun | U_z |  and 
et1.param_est(df, TZ_lon=10, time_int='hours', z_msl=50, lon=5).

But delta is only calculated with a daily data set.
et1.eto_fao() stops with the keyError delta.

Best regard!

**Comment by mullenkamp** [comment]
Hi!
Thanks for that. I never wrote a proper test case for hourly data.
I'll get to that within a week.

**Comment by mullenkamp** [comment]
Should be fixed in the new version (1.1.0) via the PR #5 .
Please check the docs (and docstrings) for some minor API changes I made.
Let me know if you have any other issues.
